2016-10-18 14:30 : 
 Traceback (most recent call last):
  File "./main.py", line 136, in <module>
    trips = [item for item in ticket_dates]
Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?
 
2016-10-18 15:00 : 
 Traceback (most recent call last):
  File "./main.py", line 136, in <module>
    trips = [item for item in ticket_dates]
Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?
 
2016-10-18 15:30 : 
 Traceback (most recent call last):
  File "./main.py", line 136, in <module>
    trips = [item for item in ticket_dates]
Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?
 
2016-10-18 16:00 : 
 Traceback (most recent call last):
  File "./main.py", line 136, in <module>
    trips = [item for item in ticket_dates]
Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?
 
2016-10-18 16:30 : 
 Traceback (most recent call last):
  File "./main.py", line 136, in <module>
    trips = [item for item in ticket_dates]
Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?
 
2016-10-18 16:30 : 
 Traceback (most recent call last):
  File "main.py", line 135, in <module>
    trips = [item for item in ticket_dates]
Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?
 
2016-10-18 16:39 : 
 Traceback (most recent call last):
  File "main.py", line 139, in <module>
    find_one_dollar_fare(trip, browser)
  File "main.py", line 70, in find_one_dollar_fare
    TargetMonth = int(data[1])
IndexError: list index out of range
 
2016-11-21 19:29 : 
 Traceback (most recent call last):
  File "main.py", line 138, in <module>
    find_one_dollar_fare(trip, browser)
  File "main.py", line 74, in find_one_dollar_fare
    CurrentMonth = MonthList.index(month.text) + 1
ValueError: u'November, 2016' is not in list
 
2016-11-21 19:30 : 
 Traceback (most recent call last):
  File "./main.py", line 138, in <module>
    find_one_dollar_fare(trip, browser)
  File "./main.py", line 74, in find_one_dollar_fare
    CurrentMonth = MonthList.index(month.text) + 1
ValueError: u'November, 2016' is not in list
 
2016-12-17 12:09 : 
 Traceback (most recent call last):
  File "main.py", line 138, in <module>
    find_one_dollar_fare(trip, browser)
  File "main.py", line 74, in find_one_dollar_fare
    CurrentMonth = MonthList.index(month.text) + 1
ValueError: u'December, 2016' is not in list
 
